development:
  adapter: postgresql
  enconding: unicode
  database: data-receiver-dev
  host: 192.168.0.254
  port: 5432
  pool: 5
  username: postgres
  password: admin

production:
  database: data-receiver
  adapter: postgresql
  host: sampaiogustavo.ddns.net
  username: postgres
  password: admin
